name: sync to azure repos

on:
  push:
     branches:
       - master

jobs:
  sync:
  runs-on: ubuntu-latest
   steps:
       - name: checkout github repository
         uses: actions/checkout@v4
         with:
             fetch-depth:0
        - name: mirror to azure devops
        run:AZURE_URL="https://x-token-auth:${{ secrets.AZURE_DEVOPS_TOKEN }}@://azure.com<ORGANIZATION>/<PROJECT>/_git/<REPO_NAME>"
          git push $AZURE_URL main --force
